/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingDesign_Class1;

import javax.swing.JOptionPane;

public class SwingDesign_Class extends javax.swing.JFrame {
    
    double value1;
    double value2;
    double result;
    Calculate calculate = new Calculate();  
    
    /**
     * Creates new form SwingDesign_Class
     */
    public SwingDesign_Class() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        ExampleLabel = new javax.swing.JLabel();
        SendButton = new javax.swing.JButton();
        LabelValue1 = new javax.swing.JLabel();
        ResultLabel = new javax.swing.JLabel();
        LabelValue2 = new javax.swing.JLabel();
        TextValue1 = new javax.swing.JTextField();
        EqualsLabel = new javax.swing.JLabel();
        TextValue2 = new javax.swing.JTextField();
        SignLabel = new javax.swing.JLabel();
        Result1 = new javax.swing.JLabel();
        AddRadioButtom = new javax.swing.JRadioButton();
        MultiplicateRadioButtom = new javax.swing.JRadioButton();
        SubstractRadioButtom = new javax.swing.JRadioButton();
        DivisionRadioButtom = new javax.swing.JRadioButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 209, 117));

        ExampleLabel.setFont(new java.awt.Font("Noto Serif Cond", 0, 18)); // NOI18N
        ExampleLabel.setForeground(new java.awt.Color(102, 51, 255));
        ExampleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExampleLabel.setText("Calculator with Java");
        ExampleLabel.setOpaque(true);

        SendButton.setText("Calculate");
        SendButton.setActionCommand("SendButton");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        LabelValue1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValue1.setText("Value 1");

        ResultLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultLabel.setText("0");
        ResultLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LabelValue2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelValue2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValue2.setText("Value 2");

        TextValue1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextValue1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValue1ActionPerformed(evt);
            }
        });

        EqualsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EqualsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EqualsLabel.setText("=");

        TextValue2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextValue2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValue2ActionPerformed(evt);
            }
        });

        SignLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignLabel.setText("+");

        Result1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Result1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result1.setText("Result");
        Result1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddRadioButtom.setText("Add");
        AddRadioButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRadioButtomActionPerformed(evt);
            }
        });

        MultiplicateRadioButtom.setText("Multiplicate");
        MultiplicateRadioButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicateRadioButtomActionPerformed(evt);
            }
        });

        SubstractRadioButtom.setText("Substract");
        SubstractRadioButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubstractRadioButtomActionPerformed(evt);
            }
        });

        DivisionRadioButtom.setText("Division");
        DivisionRadioButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionRadioButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextValue1)
                                    .addComponent(LabelValue1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AddRadioButtom)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SignLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelValue2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(TextValue2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EqualsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubstractRadioButtom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MultiplicateRadioButtom)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DivisionRadioButtom)
                            .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Result1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EqualsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignLabel)
                    .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRadioButtom)
                    .addComponent(DivisionRadioButtom)
                    .addComponent(MultiplicateRadioButtom)
                    .addComponent(SubstractRadioButtom))
                .addGap(26, 26, 26)
                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        value1 = Double.parseDouble(TextValue1.getText());
        value2 = Double.parseDouble(TextValue2.getText());
        
        if(AddRadioButtom.isSelected())
        {
            result = calculate.Add(value1, value2);
            ResultLabel.setText(Double.toString(result));
        }
        else if(SubstractRadioButtom.isSelected())
        {
            result = calculate.Substract(value1, value2);
            ResultLabel.setText(Double.toString(result));
        }
        else if(MultiplicateRadioButtom.isSelected())
        {
            result = calculate.Multiplicate(value1, value2);
            ResultLabel.setText(Double.toString(result));
        }
        else if(DivisionRadioButtom.isSelected())
        {
            result = calculate.Division(value1, value2);
            ResultLabel.setText(Double.toString(result));
        }
    }//GEN-LAST:event_SendButtonActionPerformed

    private void TextValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValue1ActionPerformed
      
    }//GEN-LAST:event_TextValue1ActionPerformed

    private void TextValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValue2ActionPerformed

    private void AddRadioButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRadioButtomActionPerformed
        SignLabel.setText("+");
    }//GEN-LAST:event_AddRadioButtomActionPerformed

    private void SubstractRadioButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubstractRadioButtomActionPerformed
        SignLabel.setText("-");
    }//GEN-LAST:event_SubstractRadioButtomActionPerformed

    private void MultiplicateRadioButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicateRadioButtomActionPerformed
        SignLabel.setText("x");
    }//GEN-LAST:event_MultiplicateRadioButtomActionPerformed

    private void DivisionRadioButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionRadioButtomActionPerformed
        SignLabel.setText("/");
    }//GEN-LAST:event_DivisionRadioButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingDesign_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingDesign_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingDesign_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingDesign_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingDesign_Class().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddRadioButtom;
    private javax.swing.JRadioButton DivisionRadioButtom;
    private javax.swing.JLabel EqualsLabel;
    private javax.swing.JLabel ExampleLabel;
    private javax.swing.JLabel LabelValue1;
    private javax.swing.JLabel LabelValue2;
    private javax.swing.JRadioButton MultiplicateRadioButtom;
    private javax.swing.JLabel Result1;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel SignLabel;
    private javax.swing.JRadioButton SubstractRadioButtom;
    private javax.swing.JTextField TextValue1;
    private javax.swing.JTextField TextValue2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
