package jFrames;

import java.sql.Connection;
import connect.MySqlConnection;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


public class JIF_Consult extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIF_Query
     */
    public JIF_Consult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        OrderNameRadioButton = new javax.swing.JRadioButton();
        OrderAverageRadioButton = new javax.swing.JRadioButton();
        OrderBirthRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();

        OrderNameRadioButton.setText("Order by name");
        OrderNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderNameRadioButtonActionPerformed(evt);
            }
        });

        OrderAverageRadioButton.setText("Order by average grade");
        OrderAverageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderAverageRadioButtonActionPerformed(evt);
            }
        });

        OrderBirthRadioButton.setText("Order by birth date");
        OrderBirthRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBirthRadioButtonActionPerformed(evt);
            }
        });

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Aluno", "Name", "Email", "Birth Date", "Course", "Math Grade", "History Grade", "Fisics Grade", "Average", "Situation"
            }
        ));
        StudentTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                StudentTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(OrderNameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderAverageRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderBirthRadioButton)
                .addGap(295, 295, 295))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderBirthRadioButton)
                    .addComponent(OrderAverageRadioButton)
                    .addComponent(OrderNameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderNameRadioButtonActionPerformed
        Connection conn = new MySqlConnection().getConnection();
        
        String orderByName = "select * from Alunos order by nome";
    }//GEN-LAST:event_OrderNameRadioButtonActionPerformed

    private void OrderAverageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderAverageRadioButtonActionPerformed
        Connection conn = new MySqlConnection().getConnection();
        
        String orderByAverage = "select * from Alunos order by media";
    }//GEN-LAST:event_OrderAverageRadioButtonActionPerformed

    private void OrderBirthRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBirthRadioButtonActionPerformed
        Connection conn = new MySqlConnection().getConnection();
        
        String orderByBirthDate = "select * from Alunos order by dataNas";
    }//GEN-LAST:event_OrderBirthRadioButtonActionPerformed

    private void StudentTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_StudentTableComponentShown
        Connection conn = new MySqlConnection().getConnection();
       
        DefaultTableModel tblModel = (DefaultTableModel) StudentTable.getModel();
    }//GEN-LAST:event_StudentTableComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OrderAverageRadioButton;
    private javax.swing.JRadioButton OrderBirthRadioButton;
    private javax.swing.JRadioButton OrderNameRadioButton;
    private javax.swing.JTable StudentTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
